exp_name: lle # <experiment name and  name of directory to save the experimental results and logs>

train:
  warmup: true
  warmup_epoch: 1 #10
  lr_warmup: 1e-6
  train_inp: /kaggle/input/lol-dataset/lol_dataset/our485/low # <path to the directory of low-light input images for training>
  train_gt: /kaggle/input/lol-dataset/lol_dataset/our485/high # <path to the directory of high-light ground truth images for training>
  valid_inp: /kaggle/input/lol-dataset/lol_dataset/eval15/low # <path to the directory of low-light input images for validation>
  valid_gt: /kaggle/input/lol-dataset/lol_dataset/eval15/high # <path to the directory of high-light ground truth images for validation>
  batch_size: 4
  epoch: 2 #50
  lr: 1e-3
  num_workers: 0
  save_every: 2 #10
  save_slim: true # re-parameterize the model and save the re-parameterized model

test:
  test_inp: /kaggle/input/lol-dataset/lol_dataset/eval15/low # <path to the directory of raw input images for testing>
  test_gt: /kaggle/input/lol-dataset/lol_dataset/eval15/high # <path to the directory of rgb ground truth images for testing>
  num_workers: 0
  save: true

demo:
  demo_inp: /kaggle/input/lol-dataset/lol_dataset/our485/low # <path to the directory of raw input images for demonstration>
  num_workers: 0

model:
  type: original # [original, re-parameterized]: choose [original] model for training/inference or [re-parameterized] model for inference
  pretrained: false # <path to the pretrained model>, not used if set false
  need_slim: false # re-parameterize the original model
  rep_scale: 4
  channels: 12
