exp_name: sr # <experiment name and  name of directory to save the experimental results and logs>

train:
  warmup: false
  warmup_epoch: 10
  lr_warmup: 1e-6
  train_inp: /kaggle/input/bsd100/bsd100/bicubic_2x/train/LR # <path to the directory of low resolution input images for training>
  train_gt: /kaggle/input/bsd100/bsd100/bicubic_2x/train/HR # <path to the directory of rgb ground truth high resolution images for training>
  valid_inp: /kaggle/input/bsd100/bsd100/bicubic_2x/val/LR # <path to the directory of low resolution input images for validation>
  valid_gt: /kaggle/input/bsd100/bsd100/bicubic_2x/val/HR # <path to the directory of rgb ground truth high resolution images for validation>
  patch_size: 64 # input image
  batch_size: 4
  epoch: 200
  lr: 1e-4
  num_workers: 0
  save_every: 20
  save_slim: true # re-parameterize the model and save the re-parameterized model

test:
  test_inp: /kaggle/input/bsd100/bsd100/bicubic_2x/val/LR # <path to the directory of low resolution input images for testing>
  test_gt: /kaggle/input/bsd100/bsd100/bicubic_2x/val/HR # <path to the directory of ground truth high resolution images for testing>
  num_workers: 0
  save: true

demo:
  demo_inp: /kaggle/input/bsd100/bsd100/bicubic_2x/val/LR # <path to the directory of low resolution input images for demonstration>
  num_workers: 0

model:
  type: original # [original, re-parameterized]: choose [original] model for training/inference or [re-parameterized] model for inference
  pretrained: false # <path to the pretrained model>
  need_slim: false # re-parameterize the original model
  scale: 2 # scale factor 2 and 4 are supported, should have consistency with inp and gt image directory
  rep_scale: 4
  channels: 12
