name: SYENetX2Test
model_type: SRModel
scale: 2
num_gpu: 1  # set num_gpu: 0 for cpu mode
manual_seed: 0

datasets:
  test_1:  # the 1st test dataset
    name: Set5
    type: PairedImageDataset
    dataroot_gt: /kaggle/input/set5-superresolution/Set5/GTmod12
    dataroot_lq: /kaggle/input/set5-superresolution/Set5/LRbicx2
    io_backend:
      type: disk
  test_2:  # the 2nd test dataset
    name: Set14
    type: PairedImageDataset
    dataroot_gt: /kaggle/input/set14dataset/Set14/GTmod12
    dataroot_lq: /kaggle/input/set14dataset/Set14/LRbicx2
    io_backend:
      type: disk
  test_3:
    name: DIV2K100
    type: PairedImageDataset
    dataroot_gt: /kaggle/input/div2k-dataset-for-super-resolution/Dataset/DIV2K_valid_HR
    dataroot_lq: /kaggle/input/div2k-dataset-for-super-resolution/Dataset/DIV2K_valid_LR_bicubic/X2
    filename_tmpl: '{}x4'
    io_backend:
      type: disk

# network structures
network_g:
  type: SYESRX2Net

# path
path:
  pretrain_network_g: experiments/pretrained_models/syenet/syenet_x2.pth
  strict_load_g: true

# validation settings
val:
  save_img: true
  suffix: ~  # add suffix to saved images, if None, use exp name

  metrics:
    psnr: # metric name, can be arbitrary
      type: calculate_psnr
      crop_border: 2
      test_y_channel: false
    ssim:
      type: calculate_ssim
      crop_border: 2
      test_y_channel: false
